name: Test
'on':
  pull_request: {}
jobs:
  test-examples:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        examples:
        - language: Python
          example-name: batch-transfers-from-csv
          category: transactions
          script-path: ./examples/transactions/batch-transfers-from-csv/Python/run.sh
        - language: Kotlin
          example-name: batch-transfers-from-csv
          category: transactions
          script-path: ./examples/transactions/batch-transfers-from-csv/Kotlin/run.sh
        - language: Swift
          example-name: batch-transfers-from-csv
          category: transactions
          script-path: ./examples/transactions/batch-transfers-from-csv/Swift/run.sh
        - language: CSharp
          example-name: batch-transfers-from-csv
          category: transactions
          script-path: ./examples/transactions/batch-transfers-from-csv/CSharp/run.sh
        - language: Python
          example-name: construction-of-simple-transaction-string-manifests
          category: transactions
          script-path: ./examples/transactions/construction-of-simple-transaction-string-manifests/Python/run.sh
        - language: Kotlin
          example-name: construction-of-simple-transaction-string-manifests
          category: transactions
          script-path: ./examples/transactions/construction-of-simple-transaction-string-manifests/Kotlin/run.sh
        - language: Swift
          example-name: construction-of-simple-transaction-string-manifests
          category: transactions
          script-path: ./examples/transactions/construction-of-simple-transaction-string-manifests/Swift/run.sh
        - language: CSharp
          example-name: construction-of-simple-transaction-string-manifests
          category: transactions
          script-path: ./examples/transactions/construction-of-simple-transaction-string-manifests/CSharp/run.sh
        - language: Python
          example-name: construction-of-simple-transaction
          category: transactions
          script-path: ./examples/transactions/construction-of-simple-transaction/Python/run.sh
        - language: Kotlin
          example-name: construction-of-simple-transaction
          category: transactions
          script-path: ./examples/transactions/construction-of-simple-transaction/Kotlin/run.sh
        - language: Swift
          example-name: construction-of-simple-transaction
          category: transactions
          script-path: ./examples/transactions/construction-of-simple-transaction/Swift/run.sh
        - language: CSharp
          example-name: construction-of-simple-transaction
          category: transactions
          script-path: ./examples/transactions/construction-of-simple-transaction/CSharp/run.sh
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test ${{ matrix.examples.language }}-${{ matrix.examples.category }}-${{ matrix.examples.example-name }}
      run: ${{ matrix.examples.script-path }}
